/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AlumnoController;
import Entidades.Alumno;
import Main.FrontEndDesktop;
import Model.AlumnoModel;
import java.sql.Date;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Steven Villalobos
 */
public class AlumnoView extends javax.swing.JInternalFrame implements java.util.Observer{

    /**
     * Creates new form AlumnoView
     */
    
    private AlumnoController controller;
    private AlumnoModel model;
    
    public AlumnoView() {
        initComponents();
        datePicker.setFormats("dd/MM/yyyy");
        datePicker.setDate(Calendar.getInstance().getTime());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cedulaText = new javax.swing.JTextField();
        nombreText = new javax.swing.JTextField();
        telefonoText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        cedulaLabel = new javax.swing.JLabel();
        telefonoLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        fechaLabel = new javax.swing.JLabel();
        guardarButton = new javax.swing.JButton();
        datePicker = new org.jdesktop.swingx.JXDatePicker();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setForeground(java.awt.Color.white);
        setTitle("Alumno");
        setMaximumSize(new java.awt.Dimension(300, 500));
        setMinimumSize(new java.awt.Dimension(300, 500));

        cedulaLabel.setText("Cédula");

        telefonoLabel.setText("Teléfono");

        nombreLabel.setText("Nombre");

        emailLabel.setText("Email");

        fechaLabel.setText("Fecha");

        guardarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/save.png"))); // NOI18N
        guardarButton.setText("Guardar cambios");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cedulaLabel)
                    .addComponent(telefonoLabel)
                    .addComponent(nombreLabel)
                    .addComponent(emailLabel)
                    .addComponent(fechaLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(emailText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(telefonoText, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreText, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cedulaText, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datePicker, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(guardarButton)
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cedulaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cedulaLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonoLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaLabel)
                    .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(guardarButton)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
        controller.guardarAlumno();
    }//GEN-LAST:event_guardarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlumnoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlumnoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlumnoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlumnoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AlumnoView().setVisible(true);
            }
        });
    }
    public void setModel(Model.AlumnoModel model){
        this.model = model;
        model.addObserver(this);
    }
    public AlumnoModel getModel(){
        return model;
    }
    public void setController(Controller.AlumnoController controller){
        this.controller = controller;
    }
    public AlumnoController getController(){
        return this.controller;
    }
    @Override
    public void update(java.util.Observable updatedModel,Object parametros){
        Alumno alumno = model.getActual();
        
        if(model.getModo() == 1){
            cedulaText.setEditable(false);
            this.setTitle("Editar alumno");
        }
        else{
            cedulaText.setEditable(true);
            this.setTitle("Crear alumno");
        }
        
        cedulaText.setText(alumno.getCedula());
        if (model.getErrores().get("Cedula")!= null){
            cedulaText.setBorder(FrontEndDesktop.BORDER_ERROR);
            cedulaText.setToolTipText(model.getErrores().get("Cedula"));
        }
        else{
            cedulaText.setBorder(null);
            cedulaText.setToolTipText("");
        }
        nombreText.setText(alumno.getNombre());
        if (model.getErrores().get("Nombre")!= null){
            nombreText.setBorder(FrontEndDesktop.BORDER_ERROR);
            nombreText.setToolTipText(model.getErrores().get("Nombre"));
        }
        else{
            nombreText.setBorder(null);
            nombreText.setToolTipText("");
        }
        telefonoText.setText(alumno.getTelefono());
        if (model.getErrores().get("Telefono")!= null){
            telefonoText.setBorder(FrontEndDesktop.BORDER_ERROR);
            telefonoText.setToolTipText(model.getErrores().get("Telefono"));
        }
        else{
            telefonoText.setBorder(null);
            telefonoText.setToolTipText("");
        }
        emailText.setText(alumno.getEmail());
        if (model.getErrores().get("Email")!= null){
            emailText.setBorder(FrontEndDesktop.BORDER_ERROR);
            emailText.setToolTipText(model.getErrores().get("Email"));
        }
        else{
            emailText.setBorder(null);
            emailText.setToolTipText("");
        }
        datePicker.setDate(alumno.getFecha());
        if(alumno.getFecha().toString().isEmpty()){
            datePicker.setBorder(FrontEndDesktop.BORDER_ERROR);
            datePicker.setToolTipText(model.getErrores().get("Fecha"));
        }
        else{
            datePicker.setBorder(null);
            datePicker.setToolTipText("");
        }

//        fechaText.setText(alumno.getFecha().toString());
//        if (model.getErrores().get("Fecha")!= null){
//            fechaText.setBorder(FrontEndDesktop.BORDER_ERROR);
//            fechaText.setToolTipText(model.getErrores().get("Fecha"));
//        }
//        else{
//            fechaText.setBorder(null);
//            fechaText.setToolTipText("");
//        }
        this.validate();
        if (!model.getMensaje().equals("")){
            JOptionPane.showMessageDialog(this, model.getMensaje(), "",JOptionPane.INFORMATION_MESSAGE);
        }
    }
    public JTextField getCedulaText(){
        return this.cedulaText;
    }
    public JTextField getNombreText(){
        return this.nombreText;
    }
    public JTextField getEmailText(){
        return this.emailText;
    }
    public JTextField getTelefonoText(){
        return this.telefonoText;
    }
    public Date getDateFromDatePicker(){
        return new java.sql.Date(datePicker.getDate().getTime());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cedulaLabel;
    private javax.swing.JTextField cedulaText;
    private org.jdesktop.swingx.JXDatePicker datePicker;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailText;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JButton guardarButton;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreText;
    private javax.swing.JLabel telefonoLabel;
    private javax.swing.JTextField telefonoText;
    // End of variables declaration//GEN-END:variables
}
