/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import AccesoDatos.GlobalException;
import AccesoDatos.NoDataException;
import Controller.AlumnosController;
import Main.FrontEndDesktop;
import Model.AlumnosModel;
import java.util.Observable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Steven Villalobos
 */
public class AlumnosView extends javax.swing.JInternalFrame implements java.util.Observer{

    /**
     * Creates new form AlumnosView
     */
    AlumnosModel model;
    AlumnosController controller;
    
    public AlumnosView() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gruposAlu = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        alumnosTable = new javax.swing.JTable();
        agregarButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buscarFld = new javax.swing.JTextField();
        listarBTN = new javax.swing.JButton();
        RBcedula = new javax.swing.JRadioButton();
        RBnombre = new javax.swing.JRadioButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Alumnos");
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));

        alumnosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        alumnosTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        alumnosTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alumnosTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(alumnosTable);

        agregarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/add.png"))); // NOI18N
        agregarButton.setText("Agregar");
        agregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarButtonActionPerformed(evt);
            }
        });

        eliminarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/delete.png"))); // NOI18N
        eliminarButton.setText("Eliminar");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Buscar");

        buscarFld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarFldKeyReleased(evt);
            }
        });

        listarBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icons.png"))); // NOI18N
        listarBTN.setText("Listar");
        listarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarBTNActionPerformed(evt);
            }
        });

        gruposAlu.add(RBcedula);
        RBcedula.setText("Cédula");

        gruposAlu.add(RBnombre);
        RBnombre.setText("Nombre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(buscarFld, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(RBcedula)
                        .addGap(32, 32, 32)
                        .addComponent(RBnombre)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(listarBTN)
                .addGap(18, 18, 18)
                .addComponent(agregarButton)
                .addGap(18, 18, 18)
                .addComponent(eliminarButton)
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(buscarFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBcedula)
                    .addComponent(RBnombre))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarButton)
                    .addComponent(eliminarButton)
                    .addComponent(listarBTN))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alumnosTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alumnosTableMouseClicked
        if (evt.getClickCount() == 2) 
        {
            int row = this.alumnosTable.getSelectedRow();
            FrontEndDesktop.ALUMNO_VIEW.setLocation(evt.getLocationOnScreen());
            controller.editar(row);
      }
    }//GEN-LAST:event_alumnosTableMouseClicked

    private void agregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarButtonActionPerformed
        controller.agregar();
    }//GEN-LAST:event_agregarButtonActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        int row = this.alumnosTable.getSelectedRow();
        if (row!=-1){
            int resp =  JOptionPane.showConfirmDialog(this, "Desea borrar?");
            if (resp== JOptionPane.YES_OPTION){
                try {
                    controller.borrar(row);
                } catch (GlobalException ex) {
                    Logger.getLogger(AlumnosView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarButtonActionPerformed

    private void buscarFldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarFldKeyReleased

        // TODO add your handling code here:
        if(RBcedula.isSelected()){
            try{
                controller.buscarCedula();
            } catch(GlobalException ex) {
                Logger.getLogger(ProfesoresView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NoDataException ex) {  
                        Logger.getLogger(ProfesoresView.class.getName()).log(Level.SEVERE, null, ex);
            }  
        }else if(RBnombre.isSelected()){
            try{
                controller.buscarNombre();
            } catch(GlobalException ex) {
                Logger.getLogger(ProfesoresView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NoDataException ex) {  
                        Logger.getLogger(ProfesoresView.class.getName()).log(Level.SEVERE, null, ex);
            }  
        }
    }//GEN-LAST:event_buscarFldKeyReleased

    private void listarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarBTNActionPerformed
        // TODO add your handling code here:
        try{
            controller.Listar();
        } catch(GlobalException ex) {
            Logger.getLogger(ProfesoresView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_listarBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlumnosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlumnosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlumnosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlumnosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlumnosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton RBcedula;
    public javax.swing.JRadioButton RBnombre;
    private javax.swing.JButton agregarButton;
    private javax.swing.JTable alumnosTable;
    public javax.swing.JTextField buscarFld;
    private javax.swing.JButton eliminarButton;
    private javax.swing.ButtonGroup gruposAlu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listarBTN;
    // End of variables declaration//GEN-END:variables
    public void setController(Controller.AlumnosController controller){
        this.controller = controller;
    }
    public void setModel(Model.AlumnosModel model){
        this.model = model;
        model.addObserver(this);
    }
    public AlumnosModel getModel(){
        return this.model;
        
    }
    @Override
    public void update(Observable o, Object arg)
    {
        alumnosTable.setModel(model.getAlumnoTableModel());
    }
}
