/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import AccesoDatos.GlobalException;
import AccesoDatos.NoDataException;
import Controller.CiclosController;
import Main.FrontEndDesktop;
import Model.CiclosModel;
import java.sql.SQLException;
import java.util.Observable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario1
 */
public class CiclosView extends javax.swing.JInternalFrame implements java.util.Observer {

    CiclosController controller;
    CiclosModel model;
    
    public void setController(CiclosController controller){
        this.controller=controller;
    }
    public void setModel(CiclosModel model){
        this.model=model;
         model.addObserver(this);
    }

    public CiclosModel getModel() {
        return model;
    }
    public int getRow()
    {
        return this.ciclosTB.getSelectedRow();
    }
    /**
     * Creates new form CiclosView
     */
    public CiclosView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        busFld = new javax.swing.JTextField();
        RBCodigo = new javax.swing.JRadioButton();
        btnListar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ciclosTB = new javax.swing.JTable();
        RBano = new javax.swing.JRadioButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Ciclos");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jLabel1.setText("Buscar:");

        busFld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                busFldKeyReleased(evt);
            }
        });

        grupo.add(RBCodigo);
        RBCodigo.setText("Código");

        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icons.png"))); // NOI18N
        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/add.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/delete.png"))); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        ciclosTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ciclosTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ciclosTBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ciclosTB);

        grupo.add(RBano);
        RBano.setText("Año");
        RBano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBanoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(busFld, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RBCodigo)
                        .addGap(18, 18, 18)
                        .addComponent(RBano)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnListar)
                .addGap(18, 18, 18)
                .addComponent(btnAgregar)
                .addGap(18, 18, 18)
                .addComponent(btnBorrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(busFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBCodigo)
                    .addComponent(RBano))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListar)
                    .addComponent(btnAgregar)
                    .addComponent(btnBorrar))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ciclosTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ciclosTBMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int row = this.ciclosTB.getSelectedRow();
            FrontEndDesktop.CURSO_VIEW.setLocation(evt.getLocationOnScreen());
            controller.editar(row);
        }
    }//GEN-LAST:event_ciclosTBMouseClicked

    private void busFldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busFldKeyReleased
        // TODO add your handling code here:
        if(RBCodigo.isSelected()){
            try{
                controller.Buscar();
            } catch(GlobalException ex) {
                Logger.getLogger(ProfesoresView.class.getName()).log(Level.SEVERE, null, ex);
            } catch(NoDataException ex) {
                Logger.getLogger(ProfesoresView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(GruposView.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }else if(RBano.isSelected()){
            try{
                controller.BuscarAno();
            } catch(GlobalException ex) {
                Logger.getLogger(ProfesoresView.class.getName()).log(Level.SEVERE, null, ex);
            } catch(NoDataException ex) {
                Logger.getLogger(ProfesoresView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(GruposView.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }

    }//GEN-LAST:event_busFldKeyReleased

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
        try {
            controller.Listar();
        } catch (GlobalException ex) {
            Logger.getLogger(CiclosView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoDataException ex) {
            Logger.getLogger(CiclosView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        FrontEndDesktop.CURSO_VIEW.setLocation(this.btnAgregar.getLocationOnScreen());
        //FrontEndDesktop.TIPO_INSTRUMENTO_VIEW.actualiza();
        controller.preAgregar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        int row = this.ciclosTB.getSelectedRow();
        if (row!=-1){
            int resp =  JOptionPane.showConfirmDialog(this, "¿Desea borrar?","Eliminar Ciclo",0,0);
            if (resp== JOptionPane.YES_OPTION){
                try {
                    controller.eliminarCiclo(row);
                } catch (GlobalException ex) {
                    Logger.getLogger(CiclosView.class.getName()).log(Level.SEVERE, null, ex);
                } catch (NoDataException ex) {
                    Logger.getLogger(CiclosView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyReleased

    private void RBanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBanoActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton RBCodigo;
    public javax.swing.JRadioButton RBano;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnListar;
    public javax.swing.JTextField busFld;
    private javax.swing.JTable ciclosTB;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        ciclosTB.setModel(model.getCiclos());
        this.revalidate();
        if (!model.getMensaje().equals("")){
            JOptionPane.showMessageDialog(this, model.getMensaje(), "",JOptionPane.INFORMATION_MESSAGE);
        }  
    }
}
