/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CursoController;
import Entidades.Curso;
import Main.FrontEndDesktop;
import Model.CursoModel;
import java.util.Observable;

/**
 *
 * @author Usuario1
 */
public class CursoView extends javax.swing.JInternalFrame implements java.util.Observer{
    
    CursoController controller;
    CursoModel model;
    
     public CursoController getController() {
        return controller;
    }
    public void setController(CursoController controller){
        this.controller=controller;
    }
    public void setModel(CursoModel model){
        this.model=model;
         model.addObserver(this);
    }

    public CursoModel getModel() {
        return model;
    }
    /**
     * Creates new form CursoView
     */
    public CursoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        codigoFld = new javax.swing.JTextField();
        nombreFld = new javax.swing.JTextField();
        creditosFld = new javax.swing.JTextField();
        horasFld = new javax.swing.JTextField();
        cicloCmbBox = new javax.swing.JComboBox();
        carreraCmbBox = new javax.swing.JComboBox();
        btnGuardar = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Curso");

        jLabel1.setText("Código");

        jLabel2.setText("Ciclo");

        jLabel3.setText("Carrera");

        jLabel4.setText("Nombre");

        jLabel5.setText("Cantidad de Créditos");

        jLabel6.setText("Cantidad de Horas");

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/save.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(codigoFld)
                            .addComponent(cicloCmbBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(carreraCmbBox, 0, 190, Short.MAX_VALUE)
                            .addComponent(nombreFld)
                            .addComponent(creditosFld)
                            .addComponent(horasFld)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(btnGuardar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(codigoFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cicloCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(carreraCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(nombreFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(creditosFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(horasFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        this.controller.guardar();
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    public javax.swing.JComboBox carreraCmbBox;
    public javax.swing.JComboBox cicloCmbBox;
    public javax.swing.JTextField codigoFld;
    public javax.swing.JTextField creditosFld;
    public javax.swing.JTextField horasFld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JTextField nombreFld;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
       Curso cursoCurrent = model.getCurrent();        
       
       codigoFld.setText(cursoCurrent.getCodigo());
       if (model.getErrores().get("CODIGO")!=null){
            codigoFld.setBorder(FrontEndDesktop.BORDER_ERROR);
            codigoFld.setToolTipText(model.getErrores().get("CODIGO"));
        }
        else{
            codigoFld.setBorder(null);
            codigoFld.setToolTipText("");
        }
       
        nombreFld.setText(cursoCurrent.getNombre());
        if (model.getErrores().get("NOMBRE")!=null){
            nombreFld.setBorder(FrontEndDesktop.BORDER_ERROR);
            nombreFld.setToolTipText(model.getErrores().get("NOMBRE"));
        }
        else{
           nombreFld.setBorder(null);
           nombreFld.setToolTipText("");
        }
        creditosFld.setText(Integer.toString(cursoCurrent.getCreditos()));
        if (model.getErrores().get("CREDITOS")!=null){
            creditosFld.setBorder(FrontEndDesktop.BORDER_ERROR);
            creditosFld.setToolTipText(model.getErrores().get("CREDITOS"));
        }
        else{
           creditosFld.setBorder(null);
           creditosFld.setToolTipText("");
        }
        
        horasFld.setText(cursoCurrent.getHoras());
        if (model.getErrores().get("HORAS")!=null){
            horasFld.setBorder(FrontEndDesktop.BORDER_ERROR);
            horasFld.setToolTipText(model.getErrores().get("HORAS"));
        }
        else{
           horasFld.setBorder(null);
           horasFld.setToolTipText("");
        }
        
        //jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vista", "Prazo" }));
        
        //cicloCmbBox.setModel(model.getCiclos());
        
        //String[] cars = new String[] {"Volvo", "BMW", "Ford", "Mazda"};
//        cicloCmbBox.setModel(new javax.swing.DefaultComboBoxModel(model.gc()));
        //cicloCmbBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vista", "Prazo" }));
        //cicloCmbBox.setModel(model.getCiclos());
        //cicloCmbBox.setSelectedItem(cursoCurrent.getCodigo_ciclo());
//       
        cicloCmbBox.setModel(model.getCiclos());
        cicloCmbBox.setSelectedItem(cursoCurrent.getCodigo_ciclo()); 
        
        carreraCmbBox.setModel(model.getCarreras());
        carreraCmbBox.setSelectedItem(cursoCurrent.getCodigo_carrera()); 

        this.validate();
        if (!model.getMensaje().equals(""))
        {
            //JOptionPane.showMessageDialog(this, model.getMensaje(), "",JOptionPane.INFORMATION_MESSAGE,FrontEndDesktop.CARRERAS_VIEW.iconoload);
        }
    }
}
