/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import AccesoDatos.GlobalException;
import AccesoDatos.NoDataException;
import Controller.ProfesoresController;
import Main.FrontEndDesktop;
import Model.ProfesoresModel;
import java.sql.SQLException;
import java.util.Observable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Steven Villalobos
 */
public class ProfesoresView extends javax.swing.JInternalFrame implements java.util.Observer{

    /**
     * Creates new form ProfesoresView
     */
    public ProfesoresView() {
        initComponents();
    }
    private ProfesoresModel model;
    private ProfesoresController controller;
    public void setController(Controller.ProfesoresController controller){
        this.controller = controller;
    }
    public void setModel(Model.ProfesoresModel model){
        this.model = model;
        model.addObserver(this);
    }
    public ProfesoresModel getModel(){
        return this.model;
        
    }
    @Override
    public void update(Observable o, Object arg)
    {
        profesoresTable.setModel(model.getProfesorTableModel());
        this.revalidate();
        if(!model.getMensaje().equals("")){
            JOptionPane.showMessageDialog(this, model.getMensaje(), "",JOptionPane.INFORMATION_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        busquda = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        profesoresTable = new javax.swing.JTable();
        agregarButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();
        buscarFld = new javax.swing.JTextField();
        listarButton = new javax.swing.JButton();
        RBCedula = new javax.swing.JRadioButton();
        RBNombre = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Profesores");
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));

        profesoresTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        profesoresTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profesoresTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(profesoresTable);

        agregarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/add.png"))); // NOI18N
        agregarButton.setText("Agregar");
        agregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarButtonActionPerformed(evt);
            }
        });

        eliminarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/delete.png"))); // NOI18N
        eliminarButton.setText("Eliminar");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        buscarFld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarFldKeyReleased(evt);
            }
        });

        listarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icons.png"))); // NOI18N
        listarButton.setText("Listar");
        listarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarButtonActionPerformed(evt);
            }
        });

        busquda.add(RBCedula);
        RBCedula.setText("Cédula");

        busquda.add(RBNombre);
        RBNombre.setText("Nombre");

        jLabel1.setText("Buscar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(buscarFld, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RBCedula)
                        .addGap(18, 18, 18)
                        .addComponent(RBNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(listarButton)
                        .addGap(18, 18, 18)
                        .addComponent(agregarButton)
                        .addGap(18, 18, 18)
                        .addComponent(eliminarButton)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBCedula)
                    .addComponent(RBNombre)
                    .addComponent(jLabel1))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listarButton)
                    .addComponent(agregarButton)
                    .addComponent(eliminarButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarButtonActionPerformed
        FrontEndDesktop.PROFESOR_VIEW.setLocation(this.agregarButton.getLocationOnScreen());
        controller.preAgregar();   
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarButtonActionPerformed

    private void profesoresTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profesoresTableMouseClicked
        if (evt.getClickCount() == 2) 
        {
            int row = this.profesoresTable.getSelectedRow();
            FrontEndDesktop.PROFESOR_VIEW.setLocation(evt.getLocationOnScreen());
            controller.editar(row);
      }
    }//GEN-LAST:event_profesoresTableMouseClicked

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        int row = this.profesoresTable.getSelectedRow();
        if (row!=-1){
            int resp =  JOptionPane.showConfirmDialog(this, "Desea borrar?");
            if (resp== JOptionPane.YES_OPTION){
                try {
                    controller.eliminarProfesor(row);
                } catch (GlobalException ex) {
                    Logger.getLogger(ProfesoresView.class.getName()).log(Level.SEVERE, null, ex);
                } catch (NoDataException ex) {
                    Logger.getLogger(ProfesoresView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarButtonActionPerformed

    private void listarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarButtonActionPerformed
        // TODO add your handling code here:
        try{
            controller.Listar();
        } catch(GlobalException ex) {
            Logger.getLogger(ProfesoresView.class.getName()).log(Level.SEVERE, null, ex);
        } catch(NoDataException ex) {
            Logger.getLogger(ProfesoresView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_listarButtonActionPerformed

    private void buscarFldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarFldKeyReleased
        // TODO add your handling code here:
        if(RBCedula.isSelected()){
            try{
                controller.buscarProfesor();
            } catch(GlobalException ex) {
                Logger.getLogger(ProfesoresView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NoDataException ex) {  
                        Logger.getLogger(ProfesoresView.class.getName()).log(Level.SEVERE, null, ex);
            }  
        }else{
            if(RBNombre.isSelected()){
                try{
                    controller.buscarProfesorNombre();
                } catch(GlobalException ex) {
                    Logger.getLogger(ProfesoresView.class.getName()).log(Level.SEVERE, null, ex);
                } catch(NoDataException ex) {
                    Logger.getLogger(ProfesoresView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_buscarFldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfesoresView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfesoresView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfesoresView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfesoresView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfesoresView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton RBCedula;
    public javax.swing.JRadioButton RBNombre;
    private javax.swing.JButton agregarButton;
    public javax.swing.JTextField buscarFld;
    private javax.swing.ButtonGroup busquda;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listarButton;
    private javax.swing.JTable profesoresTable;
    // End of variables declaration//GEN-END:variables
}
