/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import AccesoDatos.GlobalException;
import Controller.ProfesorController;
import Entidades.Profesor;
import Main.FrontEndDesktop;
import Model.ProfesorModel;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Steven Villalobos
 */
public class ProfesorView extends javax.swing.JInternalFrame implements java.util.Observer{

    /**
     * Creates new form ProfesorView
     */
    public ProfesorView() {
        initComponents();
    }
    private ProfesorController controller;
    private ProfesorModel model;
    
    public void setModel(Model.ProfesorModel model){
        this.model = model;
        model.addObserver(this);
    }
    public ProfesorModel getModel(){
        return model;
    }
    public void setController(Controller.ProfesorController controller){
        this.controller = controller;
    }
    public ProfesorController getController(){
        return this.controller;
    }
    public JTextField getCedulaText(){
        return this.cedulaText;
    }
    public JTextField getNombreText(){
        return this.nombreText;
    }
    public JTextField getEmailText(){
        return this.emailText;
    }
    public JTextField getTelefonoText(){
        return this.telefonoText;
    }
     @Override
    public void update(java.util.Observable updatedModel,Object parametros){
        Profesor profesor = model.getActual();
        
        if(model.getModo() == 1){
            cedulaText.setEditable(false);
            this.setTitle("Editar profesor");
        }
        else{
            cedulaText.setEditable(true);
            this.setTitle("Crear profesor");
        }
        
        cedulaText.setText(profesor.getCedula());
        if (model.getErrores().get("Cedula")!= null){
            cedulaText.setBorder(FrontEndDesktop.BORDER_ERROR);
            cedulaText.setToolTipText(model.getErrores().get("Cedula"));
        }
        else{
            cedulaText.setBorder(null);
            cedulaText.setToolTipText("");
        }
        nombreText.setText(profesor.getNombre());
        if (model.getErrores().get("Nombre")!= null){
            nombreText.setBorder(FrontEndDesktop.BORDER_ERROR);
            nombreText.setToolTipText(model.getErrores().get("Nombre"));
        }
        else{
            nombreText.setBorder(null);
            nombreText.setToolTipText("");
        }
        telefonoText.setText(profesor.getTelefono());
        if (model.getErrores().get("Telefono")!= null){
            telefonoText.setBorder(FrontEndDesktop.BORDER_ERROR);
            telefonoText.setToolTipText(model.getErrores().get("Telefono"));
        }
        else{
            telefonoText.setBorder(null);
            telefonoText.setToolTipText("");
        }
        emailText.setText(profesor.getEmail());
        if (model.getErrores().get("Email")!= null){
            emailText.setBorder(FrontEndDesktop.BORDER_ERROR);
            emailText.setToolTipText(model.getErrores().get("Email"));
        }
        else{
            emailText.setBorder(null);
            emailText.setToolTipText("");
        }

        this.validate();
        if (!model.getMensaje().equals("")){
            JOptionPane.showMessageDialog(this, model.getMensaje(), "",JOptionPane.INFORMATION_MESSAGE);
        }    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cedulaLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        telefonoLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        cedulaText = new javax.swing.JTextField();
        nombreText = new javax.swing.JTextField();
        telefonoText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        guardarButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Profesor");

        cedulaLabel.setText("Cédula");

        nombreLabel.setText("Nombre");

        telefonoLabel.setText("Teléfono");

        emailLabel.setText("Email");

        guardarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/save.png"))); // NOI18N
        guardarButton.setText("Guardar cambios");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(emailLabel)
                        .addGap(18, 18, 18)
                        .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(telefonoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(telefonoText, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nombreLabel)
                        .addGap(18, 18, 18)
                        .addComponent(nombreText, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cedulaLabel)
                        .addGap(18, 18, 18)
                        .addComponent(cedulaText, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(guardarButton)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cedulaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cedulaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addGap(18, 18, 18)
                .addComponent(guardarButton)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
        controller.guardarProfesor();
    }//GEN-LAST:event_guardarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfesorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfesorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfesorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfesorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfesorView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cedulaLabel;
    private javax.swing.JTextField cedulaText;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailText;
    private javax.swing.JButton guardarButton;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreText;
    private javax.swing.JLabel telefonoLabel;
    private javax.swing.JTextField telefonoText;
    // End of variables declaration//GEN-END:variables
}
