/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import View.AlumnoView;
import View.AlumnosView;
import View.CarreraView;
import View.CarrerasView;
import View.CicloView;
import View.CiclosView;
import View.CursoView;
import View.CursosView;
import View.GrupoView;
import View.GruposView;
import View.ProfesorView;
import View.ProfesoresView;

/**
 *
 * @author Steven Villalobos
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     * @param alumnosView
     */
    public MainView(AlumnosView alumnosView, AlumnoView alumnoView,ProfesoresView profesoresView, ProfesorView profesorView, 
                    GruposView gruposView, GrupoView grupoview, CarrerasView carrerasView, CarreraView carreraView,
                    CursosView cursosView, CursoView cursoView, CiclosView ciclosView, CicloView cicloView)
    {
        initComponents();
        this.setResizable(false);
        this.jDesktopPane1.add(alumnosView);
        this.jDesktopPane1.add(alumnoView);
        this.jDesktopPane1.add(profesoresView);
        this.jDesktopPane1.add(profesorView);
        this.jDesktopPane1.add(gruposView);
        this.jDesktopPane1.add(grupoview);
        this.jDesktopPane1.add(carrerasView);
        this.jDesktopPane1.add(carreraView);
        this.jDesktopPane1.add(cursosView);
        this.jDesktopPane1.add(cursoView);
        this.jDesktopPane1.add(ciclosView);
        this.jDesktopPane1.add(cicloView);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        alumnosMenu = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        gruposMenu = new javax.swing.JMenu();
        carrerasMenu = new javax.swing.JMenu();
        ciclosMenu = new javax.swing.JMenu();
        cursosMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jDesktopPane1.setMaximumSize(new java.awt.Dimension(800, 600));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1);

        alumnosMenu.setText("Alumnos");
        alumnosMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alumnosMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(alumnosMenu);

        jMenu2.setText("Profesores");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        gruposMenu.setText("Grupos");
        gruposMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gruposMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(gruposMenu);

        carrerasMenu.setText("Carreras");
        carrerasMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carrerasMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(carrerasMenu);

        ciclosMenu.setText("Ciclos");
        ciclosMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ciclosMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(ciclosMenu);

        cursosMenu.setText("Cursos");
        cursosMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cursosMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(cursosMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alumnosMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alumnosMenuMouseClicked
        // TODO add your handling code here;
        FrontEndDesktop.ALUMNOS_VIEW.setVisible(true);
    }//GEN-LAST:event_alumnosMenuMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        FrontEndDesktop.PROFESORES_VIEW.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void gruposMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gruposMenuMouseClicked
        // TODO add your handling code here:
        FrontEndDesktop.GRUPOS_VIEW.setVisible(true);
    }//GEN-LAST:event_gruposMenuMouseClicked

    private void carrerasMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carrerasMenuMouseClicked
        // TODO add your handling code here:
        FrontEndDesktop.CARRERAS_VIEW.setVisible(true);
    }//GEN-LAST:event_carrerasMenuMouseClicked

    private void ciclosMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ciclosMenuMouseClicked
        // TODO add your handling code here:
        FrontEndDesktop.CICLOS_VIEW.setVisible(true);
    }//GEN-LAST:event_ciclosMenuMouseClicked

    private void cursosMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cursosMenuMouseClicked
        // TODO add your handling code here:
        FrontEndDesktop.CURSOS_VIEW.setVisible(true);
    }//GEN-LAST:event_cursosMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView(new AlumnosView(),new AlumnoView(), new ProfesoresView(),new ProfesorView(), 
                            new GruposView(),new GrupoView(), new CarrerasView(), new CarreraView(), 
                            new CursosView(), new CursoView(), new CiclosView(), new CicloView()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu alumnosMenu;
    private javax.swing.JMenu carrerasMenu;
    private javax.swing.JMenu ciclosMenu;
    private javax.swing.JMenu cursosMenu;
    private javax.swing.JMenu gruposMenu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
